### ISSUE TITLE
player light affects UI

### ISSUE THREAD

**Issue by smiranda** [smiranda/rl1k-dev#13]
move ui sprites above the shadow overlay

**Comment by faitdivers** [comment]
I can't understand by reading the issue description if this has anything to do with the fact that:
i) the Health text does not appear in the first screen?
ii) the portals shadowing is correct in the first screen but on the following ones they do not get shadowed?

**Comment by smiranda** [comment]
well, this should be related with the order of drawing stuff on the screen. The ui overlay should be drawn last, preceded by the shadow overlay
