### ISSUE TITLE
light frozen after level change

### ISSUE THREAD

**Issue by smiranda** [smiranda/rl1k-dev#14]
after level change, the light requires a movement to update. Should be done automatically.

**Comment by faitdivers** [comment]
The fix introduced could be optimized, but this issue can be closed after the merge.

**Comment by vascop** [comment]
With 7ca4832167c1f431c71e700b4091618182000b9b I think the 1fa85af537be38ac6feb7255879fe315a2df4aaf fix is redundant

**Comment by faitdivers** [comment]
What happens if we end up in the exact same position when jumping from one level to the other? Wouldn't the bug reappear in that situation?

If we have levels with similar configuration and the portal represents stairs, we may reencounter this problem.

What do you think, @vascop ?

**Comment by vascop** [comment]
That's true, if we jump to exactly the same x and y we have to readjust the lights based on the new walls. I guess the commit isn't redundant after all, you're right.

**Comment by faitdivers** [comment]
Okay. I'll leave this closed then.
