### ISSUE TITLE
[Bot] Add AI: bot awakens when in a neighbourhood of the player

### ISSUE THREAD

**Issue by faitdivers** [smiranda/rl1k-dev#17]
The bot would then chase the player.

**Comment by smiranda** [comment]
Ok, I suggest a first approach without pathfinding, i.e., standard sin/cos boilerplate follow

**Comment by vascop** [comment]
I add that the bot should have line of sight to the player besides being in a neighbourhood. The implemented raycasting solves this by only tracing a ray between the player and each bot and checking if there's indeed LoS.

**Comment by faitdivers** [comment]
Did not implement the raycasting as of now, but it may be a future enhancement. 
Upon merging #23 this enhancement is implemented.
