### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by davidalbertonogueira** [smiranda/rl1k-dev#21]
If player is pushed by enemy bots, the light does not follows.
![image](https://cloud.githubusercontent.com/assets/5329202/7788433/6d7507c8-0232-11e5-881b-a0ad9203b503.png)

**Comment by vascop** [comment]
This has to do with the fact that I tried to optimize light by checking player velocity. By checking if the player position is the same as in the previous frame we can probably both solve this and #14 more effectively.
