### ISSUE TITLE
Put the item placement on the json file

### ISSUE THREAD

**Issue by smiranda** [smiranda/rl1k-dev#27]
As the title says !

Now, the dummy items I currently placed in the branch dev-seb are animated. This means that we probably have to refer to those items on the map creation by some id and then use that id to load the corresponding sprite sheet in-game.

Many new moons to thee !

The branch should have been called dev-loot or something. I apologize for the unfortunate name. "dev-seb" should not be taken as a seb-only branch.

**Comment by faitdivers** [comment]
I can do this today by creating an additional object layer.

**Comment by faitdivers** [comment]
d1f0365 solves this.
