### ISSUE TITLE
Remove overhead in the addition of Bots and Markers

### ISSUE THREAD

**Issue by faitdivers** [smiranda/rl1k-dev#9]
For both bots and markers the addition is being done by reading a tile layer from the .json file and then performing the following code

``` javascript
        this.map.setCollisionBetween(126, 127, true, layers.bots);// colidable tiles
        // NOTE: convertTilemap only extracts the positions of tiles defined as collidable. 
        this.bot_bodies = handler.physics.p2.convertTilemap(this.map, layers.bots);
```

to get the tiles which were previously marked.
After that the layer is deleted.

This can probably be made easier by defining an object layer in Tiled, instead of a tile layer.

**Comment by smiranda** [comment]
Solved by faitdivers
